global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: "docs_sail"

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  myresolver:
    acme:
      email: "giluan65@hotmail.com"
      storage: "/acme.json"
      httpChallenge:
        entryPoint: web